// <auto-generated />
namespace SiscomsoftVendors_Plan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inicial3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicial3));
        
        string IMigrationMetadata.Id
        {
            get { return "201706092004560_inicial3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
